---
  - name: Configure a frontend
    block:
    - name: keepalived configuration
      template:
        src: ./templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        mode: "0644"
        owner: root
        group: root
      notify: Restart keepalived
    
    - name: Start keepalived
      service:
        name: keepalived
        state: started
        enabled: true

    - name: nginx configuration
      copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/
      notify: Restart nginx

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
    when: inventory_hostname is match("frontend*")