Vagrant.configure("2") do |config|
  # Create Ansible host

  
  config.vm.define "ansible" do |ansible|
    # ansible.vm.synced_folder  ".", "/vagrant", type: "rsync", rsync_auto: "true"
    ansible.vm.box = "ubuntu/jammy"
    ansible.vm.network "private_network", ip: "192.168.33.10"
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    # Create Ansible user and copy RSA key
    ansible.vm.provision "shell", inline: <<-SHELL
    # sudo yum install epel-release -y
    # sudo apt install ansible -y
    # sleep 10
    # sudo yum install ansible -y
    ssh-keygen -q -f /home/vagrant/.ssh/id_rsa -C vagrant -N '' 
    chown -R vagrant:vagrant /home/vagrant/.ssh
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/*
    sudo cp -R /home/vagrant/.ssh/id_rsa.pub /vagrant/
    apt update
    apt install ansible -y

    SHELL
  end

  # Create 3 frontend VMs with a 20GB disk and private network
  (1..3).each do |i|
    config.vm.define "pxc#{i}" do |pxc|
      pxc.vm.box = "centos/7"
      pxc.vm.network "private_network", ip: "192.168.33.#{13+i}"
      pxc.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      
      end
      pxc.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/"
      pxc.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant/.ssh
      chmod 700 /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/*
      SHELL
      pxc.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa_ansible.pub"
    end
  end
end
