Vagrant.configure("2") do |config|
  # Create Ansible host

  
  config.vm.define "ansible" do |ansible|
    # ansible.vm.synced_folder  ".", "/vagrant", type: "rsync", rsync_auto: "true"
    ansible.vm.box = "ubuntu/jammy"
    ansible.vm.network "private_network", ip: "192.168.33.10"
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    # Create Ansible user and copy RSA key
    ansible.vm.provision "shell", inline: <<-SHELL
    ssh-keygen -q -f /home/vagrant/.ssh/id_rsa -C vagrant -N '' 
    chown -R vagrant:vagrant /home/vagrant/.ssh
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/*
    sudo cp -R /home/vagrant/.ssh/id_rsa.pub /vagrant/
    apt update
    apt install ansible -y

    SHELL
  end

  # Create 3 PCS VMs with 2 private networks
  (1..3).each do |i|
    config.vm.define "pcs#{i}" do |pcs|
      pcs.vm.box = "centos/7"
      pcs.vm.network "private_network", ip: "192.168.33.#{10+i}"
      pcs.vm.network "private_network", ip: "192.168.34.#{10+i}"
      pcs.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      
      end
      pcs.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/"
      pcs.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant/.ssh
      chmod 700 /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/*
      SHELL
      pcs.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa_ansible.pub"
    end
  end

# Create  iSCSI host with 2 private networks
  config.vm.define "iscsi" do |iscsi|
    iscsi.vm.box = "centos/7"
    iscsi.vm.network "private_network", ip: "192.168.33.14"
    iscsi.vm.network "private_network", ip: "192.168.34.14"
    iscsi.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      
    end
    iscsi.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/"
    iscsi.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant/.ssh
      chmod 700 /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/*
      SHELL
      iscsi.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa_ansible.pub"
    end

  
end
